In [1]:
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
from mplfonts import use_font
use_font('SimHei')
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import pandas as pd
import numpy as np

In [7]:
adult = pd.read_csv("adult_with_pii.csv")
adult.iloc[:, :5]

                    Name         DOB          SSN    Zip         Workclass
0       Karrie Trusslove    9/7/1967  732-14-6110  64152         State-gov
1       Brandise Tripony    6/7/1988  150-19-2766  61523  Self-emp-not-inc
2          Brenn McNeely    8/6/1991  725-59-9860  95668           Private
3            Dorry Poter    4/6/2009  659-57-4974  25503           Private
4            Dick Honnan   9/16/1951  220-93-3811  75387           Private
...                  ...         ...          ...    ...               ...
32558       Ardyce Golby  10/29/1961  212-61-8338  41328           Private
32559      Jean O'Connor   6/28/1952  737-32-2919  94735           Private
32560   Reuben Skrzynski    8/9/1966  314-48-0219  49628           Private
32561        Caye Biddle   5/19/1978  647-75-3550   8213           Private
32562  Hortense Hardesty   5/11/2012  690-42-5638  86153      Self-emp-inc

[32563 rows x 5 columns]

In [3]:
adult_sans_pii = adult.copy().drop(columns=['Name','SSN'])
adult_pii = adult[['Name','SSN','DOB','Zip']]
adult_sans_pii.head(1).iloc[:,:5]

        DOB    Zip  Workclass  Education  Education-Num
0  9/7/1967  64152  State-gov  Bachelors             13

In [5]:
karries_row = adult_pii[adult_pii['Name'] == 'Karrie Trusslove']
r = pd.merge(karries_row,adult_sans_pii,left_on=['DOB','Zip'],right_on=['DOB','Zip'])
r['Target']

0    <=50K
Name: Target, dtype: str

In [8]:
pd.merge(karries_row,adult_sans_pii,left_on=['Zip'],right_on=['Zip']).iloc[:,:4]

               Name          SSN     DOB_x    Zip
0  Karrie Trusslove  732-14-6110  9/7/1967  64152

In [10]:
r = pd.merge(karries_row,adult_sans_pii,left_on=['DOB'],right_on=['DOB'])
r[['Target','Sex','Occupation']]

  Target     Sex       Occupation
0  <=50K    Male     Adm-clerical
1  <=50K  Female  Farming-fishing
2   >50K    Male  Exec-managerial

In [11]:
adult['Age'].mean()

np.float64(41.77250253355035)

In [12]:
adult[['Education','Age']].groupby('Education',as_index=False).mean().head(3)

  Education        Age
0      10th  42.032154
1      11th  42.057021
2      12th  41.879908

In [13]:
adult[['Zip','Age']].groupby('Zip',as_index=False).mean().head()

   Zip   Age
0    4  72.0
1   12  46.0
2   16  38.0
3   17  31.0
4   18  40.0